prometheus_url: https://prometheus-prod-01-eu-west-0.grafana.net/api/prom/push
loki_url: https://logs-prod-eu-west-0.grafana.net/loki/api/v1/push
tempo_url: https://tempo-eu-west-0.grafana.net

otlp_url: https://otlp-gateway-prod-eu-west-0.grafana.net/otlp
otlp_protocol: http/protobuf

# secrets

grafana_cloud_api_key: "{{ vault_grafana_cloud_api_key }}"
metrics_username: "{{ vault_metrics_username }}"
logs_username: "{{ vault_logs_username }}"
otlp_auth_username: "{{ vault_otlp_auth_username }}"
otlp_auth_password: "{{ vault_otlp_auth_password }}"
