---
roles:
  - name: slingnode.ethereum
  - name: slingnode.ethereum_observability
  - name: geerlingguy.docker
    version: 7.0.2
  - name: geerlingguy.pip
    version: latest
  - name: julienpalard.nginx_letsencrypt
    version: master
  - name: ethersphere.bee
    version: main

collections:
  - name: community.docker
    version: 3.12.1
  - name: grafana.grafana
    version: 5.2.0
# - name: ethpandaops.general
#   source: https://github.com/ethpandaops/ansible-collection-general.git,master
#   type: git
